name    'jhoblitt-mdadm'
version '0.0.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-mdadm'
source 'https://github.com/jhoblitt/puppet-mdadm.git'
summary 'Manages the `mdadm` util for Linux software RAID arrays'
description 'Manages the `mdadm` util for Linux software RAID arrays'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
